name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} >> .env
          echo MUMBAI_API_KEY=${{ secrets.MUMBAI_API_KEY }} >> .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
          echo POLYSCAN_API_KEY=${{ secrets.POLYSCAN_API_KEY }} >> .env

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

      - name: Run hardhat tests
        run: npx hardhat test
